가장 간단한 방법으로 허깅페이스 사전학습 모델을 활용한 텍스트 분류를 진행합니다.

In [1]:
import os
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

from Korpora import Korpora

os.environ["TOKENIZERS_PARALLELISM"] = 'true'

# device 지정
device = torch.device('cuda:1' if torch.cuda.is_available() else 'cpu')
print(device)

corpus = Korpora.load("nsmc")

cuda:1

    Korpora 는 다른 분들이 연구 목적으로 공유해주신 말뭉치들을
    손쉽게 다운로드, 사용할 수 있는 기능만을 제공합니다.

    말뭉치들을 공유해 주신 분들에게 감사드리며, 각 말뭉치 별 설명과 라이센스를 공유 드립니다.
    해당 말뭉치에 대해 자세히 알고 싶으신 분은 아래의 description 을 참고,
    해당 말뭉치를 연구/상용의 목적으로 이용하실 때에는 아래의 라이센스를 참고해 주시기 바랍니다.

    # Description
    Author : e9t@github
    Repository : https://github.com/e9t/nsmc
    References : www.lucypark.kr/docs/2015-pyconkr/#39

    Naver sentiment movie corpus v1.0
    This is a movie review dataset in the Korean language.
    Reviews were scraped from Naver Movies.

    The dataset construction is based on the method noted in
    [Large movie review dataset][^1] from Maas et al., 2011.

    [^1]: http://ai.stanford.edu/~amaas/data/sentiment/

    # License
    CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
    Details in https://creativecommons.org/publicdomain/zero/1.0/

[Korpora] Corpus `nsmc` is already installed at /root/Korpora/nsmc/ratings_train.txt
[Korpora] Corpus `nsmc` is already installed at /root/Korpora/

네이버 영화 댓글 데이터셋 로드

In [2]:
import pandas as pd

train = pd.read_csv('~/Korpora/nsmc/ratings_train.txt', sep='\t')
test = pd.read_csv('~/Korpora/nsmc/ratings_test.txt', sep='\t')

In [3]:
train['length'] = train['document'].apply(lambda x: len(str(x)))
test['length'] = test['document'].apply(lambda x: len(str(x)))

In [4]:
train = train.loc[train['length'] > 5]
train = train.sample(1000)
train

id                                           document  label  \
108714  6144332                                            너무 좋아 ㅋ      1   
36356   7902514  평범 1점도 아까운 쓰레기 애니, 5살 애들 조차 유치하다고 하는, 유치하기도 하고...      0   
23424   5900523                               이런 작품은 그냥 닥치고 별 10개.      1   
26058   5530316                              처음은 신선했으나.. 무섭지 않아서..      0   
114325  7502965  아오 보면서 욕나오네 아침부터 짜증이 확 밀려온다 첨부터 봐서 걍 보려고 했는데 다...      0   
...         ...                                                ...    ...   
74078   9770576                                      기분좋은날봤다가 아열받아      0   
114095    72623                               어릴때 멋모르고 본 시간 낭비인 영화      0   
29495   9303674  이야기를 알고 보면 더 보이는 영화.영상미와 사운드가 압도적인영화.볼때마다 느낌이 ...      1   
34199   9434809  김종국 왜그래??맨날 지혼자 힘쌘척하고 자기가 무슨재일 나이가 많은것도 아니면서 맨...      0   
113921  9249452                                         12세이상관람불가.      0   

        length  
108714       7  
36356      101  
23424       20  
26058       21  
114325      50  
...        ...  
74078       13  
114095      20  
29495       70  
34199       98  
113921      10  

[1000 rows x 4 columns]

In [5]:
test = test.loc[test['length'] > 5]
test = test.sample(500)
test

id                                           document  label  \
2370    1983144                                            설정은 좋은데      0   
28060    591691                                      개코메디를 원하신다면!!      1   
42945   4154245            문화적 이질감... 단지 여유로운 타국 생활의 동경을 일으킬 정도...      0   
14313   8937594                                       친일오유 망해버려라 ㅇ      1   
35426   8812102  김민정 혼자 악전고투하는구나...천정명과 기타 조연들의 어색한 연기...임산부에게 ...      0   
...         ...                                                ...    ...   
41218   6616327                                     송윤아 노래만 기억남는다.      0   
8555    9142731                                    반전도 그렇고 재밌었어요 ㅎ      1   
40838   5845832                         어째 이감독은 변화가없냐.. 이건 리얼쓰레기..      0   
2938   10121578                        쓰레기같은 늙은이를 세인트로 만들려는 억지 스토리      0   
23512   1190795                                두말할꺼 없이 성룡영화중 최고!!!      1   

       length  
2370        7  
28060      13  
42945      39  
14313      12  
35426     108  
...       ...  
41218      14  
8555       15  
40838      26  
2938       27  
23512      19  

[500 rows x 4 columns]

## 토큰화가 적용된 데이터셋

In [6]:
CHECKPOINT_NAME = 'kykim/bert-kor-base'

In [7]:
import torch
from transformers import BertTokenizerFast
from torch.utils.data import Dataset, DataLoader


class TokenDataset(Dataset):
  
    def __init__(self, dataframe, tokenizer_pretrained):
        # sentence, label 컬럼으로 구성된 데이터프레임 전달
        self.data = dataframe        
        # Huggingface 토크나이저 생성
        self.tokenizer = BertTokenizerFast.from_pretrained(tokenizer_pretrained)
  
    def __len__(self):
        return len(self.data)
  
    def __getitem__(self, idx):
        sentence = self.data.iloc[idx]['document']
        label = self.data.iloc[idx]['label']

        # 토큰화 처리
        tokens = self.tokenizer(
            sentence,                # 1개 문장 
            return_tensors='pt',     # 텐서로 반환
            truncation=True,         # 잘라내기 적용
            padding='max_length',    # 패딩 적용
            add_special_tokens=True  # 스페셜 토큰 적용
        )

        input_ids = tokens['input_ids'].squeeze(0)           # 2D -> 1D
        attention_mask = tokens['attention_mask'].squeeze(0) # 2D -> 1D
        token_type_ids = torch.zeros_like(attention_mask)

        return {
            'input_ids': input_ids,
            'attention_mask': attention_mask, 
            'token_type_ids': token_type_ids,
        }, torch.tensor(label)
    

데이터셋 인스턴스 생성

In [8]:
# 토크나이저 지정
tokenizer_pretrained = CHECKPOINT_NAME

# train, test 데이터셋 생성
train_data = TokenDataset(train, tokenizer_pretrained)
test_data = TokenDataset(test, tokenizer_pretrained)

train_loader = DataLoader(train_data, batch_size=8, shuffle=True, num_workers=8)
test_loader = DataLoader(test_data, batch_size=8, shuffle=True, num_workers=8)

In [9]:
inputs, labels = next(iter(train_loader))
inputs = {k: v.to(device) for k, v in inputs.items()}
labels.to(device)

tensor([1, 1, 0, 0, 1, 1, 1, 1], device='cuda:1')

In [10]:
inputs.keys()

dict_keys(['input_ids', 'attention_mask', 'token_type_ids'])

In [11]:
inputs['input_ids'].shape, inputs['attention_mask'].shape, inputs['token_type_ids'].shape

(torch.Size([8, 512]), torch.Size([8, 512]), torch.Size([8, 512]))

In [12]:
labels

tensor([1, 1, 0, 0, 1, 1, 1, 1])

## Model

In [13]:
from transformers import BertModel, BertConfig

model_bert = BertModel.from_pretrained(CHECKPOINT_NAME).to(device)
model_bert

Some weights of the model checkpoint at kykim/bert-kor-base were not used when initializing BertModel: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(42000, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          

In [14]:
config = BertConfig.from_pretrained(CHECKPOINT_NAME)
config

BertConfig {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "embedding_size": 768,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.22.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 42000
}

In [15]:
output = model_bert(**inputs)
output.keys()

odict_keys(['last_hidden_state', 'pooler_output'])

In [16]:
last_hidden = output['last_hidden_state']
print(last_hidden.shape)
print(last_hidden[:, 0, :])

torch.Size([8, 512, 768])
tensor([[-0.2983, -0.6834,  0.2263,  ..., -0.6870, -0.8065,  0.1505],
        [-0.7467, -1.3713,  0.1558,  ..., -1.2442, -0.4519,  0.7864],
        [ 0.1995,  0.1691,  0.0295,  ...,  0.0838, -0.8285,  0.8101],
        ...,
        [-0.7254, -0.1449, -0.5475,  ...,  0.3946,  0.3268, -0.4981],
        [-1.4925, -0.4569, -0.6353,  ..., -1.2705, -0.7173, -0.2611],
        [ 0.1087,  0.1951, -0.8966,  ..., -0.0968, -0.6808, -0.3470]],
       device='cuda:1', grad_fn=<SliceBackward0>)


In [17]:
fc = nn.Linear(768, 2)
fc.to(device)
fc_output = fc(last_hidden[:, 0, :])
print(fc_output.shape)
print(fc_output.argmax(dim=1))

torch.Size([8, 2])
tensor([1, 0, 0, 0, 0, 0, 0, 1], device='cuda:1')


In [18]:
class CustomBertModel(nn.Module):
    def __init__(self, bert_pretrained, dropout_rate=0.5):
        super(CustomBertModel, self).__init__()
        self.bert = BertModel.from_pretrained(bert_pretrained)
        self.dr = nn.Dropout(p=dropout_rate)
        self.fc = nn.Linear(768, 2)
    
    def forward(self, input_ids, attention_mask, token_type_ids):
        output = self.bert(input_ids=input_ids, attention_mask=attention_mask, token_type_ids=token_type_ids)
        last_hidden = output['last_hidden_state']
        x = self.dr(last_hidden[:, 0, :])
        x = self.fc(x)
        return x

In [29]:
bert = CustomBertModel(CHECKPOINT_NAME)
bert.to(device)

Some weights of the model checkpoint at kykim/bert-kor-base were not used when initializing BertModel: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


CustomBertModel(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(42000, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=Tr

In [30]:
loss_fn = nn.CrossEntropyLoss()
# 옵티마이저 설정: model.paramters()와 learning_rate 설정
optimizer = optim.Adam(bert.parameters(), lr=1e-5)

In [40]:
from tqdm import tqdm  # Progress Bar 출력

def model_train(model, data_loader, loss_fn, optimizer, device):
    # 모델을 훈련모드로 설정합니다. training mode 일 때 Gradient 가 업데이트 됩니다. 반드시 train()으로 모드 변경을 해야 합니다.
    model.train()
    
    # loss와 accuracy 계산을 위한 임시 변수 입니다. 0으로 초기화합니다.
    running_loss = 0
    corr = 0
    counts = 0
    
    # 예쁘게 Progress Bar를 출력하면서 훈련 상태를 모니터링 하기 위하여 tqdm으로 래핑합니다.
    prograss_bar = tqdm(data_loader, unit='batch', total=len(data_loader), mininterval=1)
    
    # mini-batch 학습을 시작합니다.
    for idx, (inputs, labels) in enumerate(prograss_bar):
        # inputs, label 데이터를 device 에 올립니다. (cuda:0 혹은 cpu)
        inputs = {k:v.to(device) for k, v in inputs.items()}
        labels = labels.to(device)
        
        # 누적 Gradient를 초기화 합니다.
        optimizer.zero_grad()
        
        # Forward Propagation을 진행하여 결과를 얻습니다.
        output = model(**inputs)
        
        # 손실함수에 output, label 값을 대입하여 손실을 계산합니다.
        loss = loss_fn(output, labels)
        
        # 오차역전파(Back Propagation)을 진행하여 미분 값을 계산합니다.
        loss.backward()
        
        # 계산된 Gradient를 업데이트 합니다.
        optimizer.step()
        
        # output의 max(dim=1)은 max probability와 max index를 반환합니다.
        # max probability는 무시하고, max index는 pred에 저장하여 label 값과 대조하여 정확도를 도출합니다.
        _, pred = output.max(dim=1)
        
        # pred.eq(lbl).sum() 은 정확히 맞춘 label의 합계를 계산합니다. item()은 tensor에서 값을 추출합니다.
        # 합계는 corr 변수에 누적합니다.
        corr += pred.eq(labels).sum().item()
        counts += len(labels)
        
        # loss 값은 1개 배치의 평균 손실(loss) 입니다. img.size(0)은 배치사이즈(batch size) 입니다.
        # loss 와 img.size(0)를 곱하면 1개 배치의 전체 loss가 계산됩니다.
        # 이를 누적한 뒤 Epoch 종료시 전체 데이터셋의 개수로 나누어 평균 loss를 산출합니다.
        running_loss += loss.item() * labels.size(0)
        
        prograss_bar.set_description(f"training loss: {running_loss/(idx+1):.5f}, training accuracy: {corr / counts:.5f}")
        
    # 누적된 정답수를 전체 개수로 나누어 주면 정확도가 산출됩니다.
    acc = corr / len(data_loader.dataset)
    
    # 평균 손실(loss)과 정확도를 반환합니다.
    # train_loss, train_acc
    return running_loss / len(data_loader.dataset), acc

In [41]:
def model_evaluate(model, data_loader, loss_fn, device):
    # model.eval()은 모델을 평가모드로 설정을 바꾸어 줍니다. 
    # dropout과 같은 layer의 역할 변경을 위하여 evaluation 진행시 꼭 필요한 절차 입니다.
    model.eval()
    
    # Gradient가 업데이트 되는 것을 방지 하기 위하여 반드시 필요합니다.
    with torch.no_grad():
        # loss와 accuracy 계산을 위한 임시 변수 입니다. 0으로 초기화합니다.
        corr = 0
        running_loss = 0
        
        # 배치별 evaluation을 진행합니다.
        for inputs, labels in data_loader:
            # inputs, label 데이터를 device 에 올립니다. (cuda:0 혹은 cpu)
            inputs = {k:v.to(device) for k, v in inputs.items()}
            labels = labels.to(device)
            
            # 모델에 Forward Propagation을 하여 결과를 도출합니다.
            output = model(**inputs)
            
            # output의 max(dim=1)은 max probability와 max index를 반환합니다.
            # max probability는 무시하고, max index는 pred에 저장하여 label 값과 대조하여 정확도를 도출합니다.
            _, pred = output.max(dim=1)
            
            # pred.eq(lbl).sum() 은 정확히 맞춘 label의 합계를 계산합니다. item()은 tensor에서 값을 추출합니다.
            # 합계는 corr 변수에 누적합니다.
            corr += torch.sum(pred.eq(labels)).item()
            
            # loss 값은 1개 배치의 평균 손실(loss) 입니다. img.size(0)은 배치사이즈(batch size) 입니다.
            # loss 와 img.size(0)를 곱하면 1개 배치의 전체 loss가 계산됩니다.
            # 이를 누적한 뒤 Epoch 종료시 전체 데이터셋의 개수로 나누어 평균 loss를 산출합니다.
            running_loss += loss_fn(output, labels).item() * labels.size(0)
        
        # validation 정확도를 계산합니다.
        # 누적한 정답숫자를 전체 데이터셋의 숫자로 나누어 최종 accuracy를 산출합니다.
        acc = corr / len(data_loader.dataset)
        
        # 결과를 반환합니다.
        # val_loss, val_acc
        return running_loss / len(data_loader.dataset), acc

In [42]:
# 최대 Epoch을 지정합니다.
num_epochs = 10
model_name = 'bert-kor-base'

min_loss = np.inf

# Epoch 별 훈련 및 검증을 수행합니다.
for epoch in range(num_epochs):
    # Model Training
    # 훈련 손실과 정확도를 반환 받습니다.
    train_loss, train_acc = model_train(bert, train_loader, loss_fn, optimizer, device)

    # 검증 손실과 검증 정확도를 반환 받습니다.
    val_loss, val_acc = model_evaluate(bert, test_loader, loss_fn, device)   
    
    # val_loss 가 개선되었다면 min_loss를 갱신하고 model의 가중치(weights)를 저장합니다.
    if val_loss < min_loss:
        print(f'[INFO] val_loss has been improved from {min_loss:.5f} to {val_loss:.5f}. Saving Model!')
        min_loss = val_loss
        torch.save(bert.state_dict(), f'{model_name}.pth')
    
    # Epoch 별 결과를 출력합니다.
    print(f'epoch {epoch+1:02d}, loss: {train_loss:.5f}, acc: {train_acc:.5f}, val_loss: {val_loss:.5f}, val_accuracy: {val_acc:.5f}')

training loss: 0.56740, training accuracy: 0.97600: 100% 125/125 [00:20<00:00,  6.17batch/s]


[INFO] val_loss has been improved from inf to 0.54247. Saving Model!
epoch 01, loss: 0.07093, acc: 0.97600, val_loss: 0.54247, val_accuracy: 0.85200


training loss: 0.38700, training accuracy: 0.98600: 100% 125/125 [00:20<00:00,  6.15batch/s]


epoch 02, loss: 0.04838, acc: 0.98600, val_loss: 0.56429, val_accuracy: 0.85800


training loss: 0.31164, training accuracy: 0.98700: 100% 125/125 [00:20<00:00,  6.13batch/s]


epoch 03, loss: 0.03895, acc: 0.98700, val_loss: 0.60210, val_accuracy: 0.85800


training loss: 0.17115, training accuracy: 0.99200: 100% 125/125 [00:20<00:00,  6.10batch/s]


epoch 04, loss: 0.02139, acc: 0.99200, val_loss: 0.69282, val_accuracy: 0.84800


training loss: 0.27327, training accuracy: 0.98600: 100% 125/125 [00:20<00:00,  6.13batch/s]


epoch 05, loss: 0.03416, acc: 0.98600, val_loss: 0.75029, val_accuracy: 0.86800


training loss: 0.22501, training accuracy: 0.98800: 100% 125/125 [00:20<00:00,  6.12batch/s]


epoch 06, loss: 0.02813, acc: 0.98800, val_loss: 0.70921, val_accuracy: 0.84600


training loss: 0.17293, training accuracy: 0.99100: 100% 125/125 [00:20<00:00,  6.13batch/s]


epoch 07, loss: 0.02162, acc: 0.99100, val_loss: 0.67326, val_accuracy: 0.86000


training loss: 0.10512, training accuracy: 0.99400: 100% 125/125 [00:20<00:00,  6.13batch/s]


epoch 08, loss: 0.01314, acc: 0.99400, val_loss: 0.80222, val_accuracy: 0.85200


training loss: 0.19056, training accuracy: 0.99100: 100% 125/125 [00:20<00:00,  6.13batch/s]


epoch 09, loss: 0.02382, acc: 0.99100, val_loss: 0.75769, val_accuracy: 0.84400


training loss: 0.30627, training accuracy: 0.98600: 100% 125/125 [00:20<00:00,  6.12batch/s]


epoch 10, loss: 0.03828, acc: 0.98600, val_loss: 0.73346, val_accuracy: 0.84600
